name: qrscan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  equatable: ^2.0.7
  flutter_bloc: ^8.1.1
  flutter_inset_box_shadow: ^1.0.8
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  local_auth: ^2.3.0
  sqflite: ^2.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  pigeon: ^22.7.0
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

