name: qrscan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  flutter_inset_box_shadow: ^1.0.8
  flutter_keyboard_visibility: ^6.0.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  local_auth: ^2.3.0
  mockito: ^5.0.16
  permission_handler: ^11.0.1
  pinput: ^5.0.0
  sqflite: ^2.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  path: any
  pigeon: ^22.7.0
  mockito: ^5.0.16
  sqflite_common_ffi: any
  test: ^1.16.0

flutter:

  uses-material-design: true

